---

- name: install jenkins apt key
  apt_key: 
    url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"

- name: install the repo
  apt_repository: 
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"

- name: install jenkins
  apt:
    update_cache: True
    cache_valid_time: 3600
    name: jenkins

- name: obtain jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_admin_password
  changed_when: False

- set_fact:
    jenkins_admin_password: "{{ initial_admin_password.stdout }}"

- debug:
    msg: "The admin password is {{ jenkins_admin_password }}"
    verbosity: 2