---

- name: install jenkins apt key
  apt_key: 
    url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"

- name: install the repo
  apt_repository: 
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"

- name: install jenkins
  apt:
    update_cache: True
    cache_valid_time: 3600
    name: jenkins

#- name: obtain jenkins initial admin password
#  shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
#  register: jenkins_unlock

#- name: Show Jenkins unlock code
#  debug: msg="Jenkins unlock code (admin) is {{ jenkins_unlock.stdout }}"

- name: config_jenkins | Disabling Jenkins Setup Wizard
  lineinfile:
    dest: "/var/lib/jenkins/"
    regexp: "^{{ jenkins_java_options }}="
    line: "{{ jenkins_java_options }}=\"-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false\""
  become: true
  register: "jenkins_setup_wizard_disabled"
 # when: jenkins_config_info['disable_setup_wizard']
