---
- name: Install Jfrog as a .deb package
  apt:
    deb: https://api.bintray.com/content/jfrog/artifactory-debs/pool/main/j/jfrog-artifactory-oss-deb/jfrog-artifactory-oss-$latest.deb;bt_package=jfrog-artifactory-oss-deb

- name: artifactory | Start/Restart artifactory 
  service: name=artifactory state=started
